name = "tensor_sieve"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TensorSieve"]
testDriver = "Tests"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"


[[lean_lib]]
name = "TensorSieve"

[[lean_lib]]
name = "PTSymmetry"

[[lean_exe]]
name = "tensor_sieve"
root = "Main"

[[lean_exe]]
name = "Tests"
root = "Tests"

