"""
visualize_spectrum.py

Visualizes the GUE energy landscape dynamically generated by the non-Archimedean 
p-adic shift operator in Lean 4.

This script ingests the 'data.csv' output from the tensor_sieve executable, 
mapping the horizontal cross-branch trace signature to plot:
1. Trace Formula Convergence (Cumulative Zeroes / Energy Levels)
2. Arithmetic Divergence (Dynamic Eigenvalue Spacing / Local Degree)
"""

import csv
import matplotlib.pyplot as plt
import sys
import os

def main():
    """
    Main entry point for the visualization script.
    Checks for the data file, processes the output, and generates the spectral plot.
    """
    if not os.path.exists('data.csv'):
        print("data.csv not found. Did you run `lake exe tensor_sieve > data.csv`?")
        sys.exit(1)
        
    xs = []
    spacings = []
    
    # Parse the emitted stream from the Lean executable
    with open('data.csv', 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            xs.append(int(row['x']))
            # We use local_degree as the structural analog for spectral weight/divergence
            deg = int(row['local_degree'])
            spacings.append(deg)

    if not xs:
        print("No data found in data.csv. Sieve failed to generate output.")
        sys.exit(1)

    # Configure the plot layout
    plt.figure(figsize=(12, 6))
    
    # Plot 1: Trace Formula Convergence (Cumulative Zeros / Energy Levels)
    # This plots the trajectory of the discrete sieve traversing the p-adic tree.
    plt.subplot(1, 2, 1)
    levels = range(1, len(xs) + 1)
    plt.plot(levels, xs, marker='.', linestyle='-', color='red')
    plt.title('Non-Archimedean Sieve Trajectory')
    plt.xlabel('Contraction Step')
    plt.ylabel('Semantic Address (x)')
    plt.yscale('log')
    plt.grid(True)
    
    # Plot 2: Eigenvalue Spacing Distribution (Arithmetic Divergence)
    # This visualizes the topological tension creating the discrete jamming events.
    plt.subplot(1, 2, 2)
    plt.hist(spacings, bins=max(10, len(set(spacings))), alpha=0.7, color='blue', edgecolor='black')
    plt.title('Arithmetic Divergence (Local Degree)')
    plt.xlabel('Local Degree (D)')
    plt.ylabel('Frequency')
    plt.grid(True)
    
    # Save the output to disk
    plt.tight_layout()
    plt.savefig('spectrum_visualization.png')
    print("Saved visualization to spectrum_visualization.png")

if __name__ == '__main__':
    main()
