import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Data.Nat.Factorization.Basic
import Mathlib.Data.Nat.Factors
import Mathlib.Combinatorics.Quiver.Basic
import Mathlib.Data.Finsupp.Basic
import Mathlib.Data.Finset.Basic

namespace KinematicRiemann

open Finset
open Classical

/-- A SemanticAddress is a static record of unique prime factorization.
    We enforce the requirement that the integer strictly exists. -/
structure SemanticAddress where
  val : ℕ
  pos : 0 < val

/-- Two addresses are connected if they are separated by exactly one prime generator. -/
def isPrimeStep (a b : SemanticAddress) : Prop :=
  ∃ p : ℕ, p.Prime ∧ b.val = a.val * p

/-- The Bruhat-Tits lattice represented as a directed Quiver graph. -/
instance : Quiver SemanticAddress where
  Hom a b := PLift (isPrimeStep a b)

/-- The total number of prime factors counting multiplicities. -/
noncomputable def primeWeight (a : SemanticAddress) : ℕ :=
  a.val.factorization.sum (fun _ v => v)

/-- The local combinatorial degree D of an address based on its finite p-adic history. -/
noncomputable def localDegree (a : SemanticAddress) : ℕ :=
  a.val.factorization.sum (fun _ v => v)

/-- The unnormalized combinatorial Laplacian L_c = D - K -/
noncomputable def adjacency (a b : SemanticAddress) : ℤ :=
  if isPrimeStep a b ∨ isPrimeStep b a then 1 else 0

noncomputable def combinatorialLaplacian (a b : SemanticAddress) : ℤ :=
  if a.val == b.val then
    (localDegree a : ℤ)
  else
    - (adjacency a b)

/-- The well-founded relation dictating operator traversal through divisibility.
    a ≺ b means a logically precedes b by being a proper divisor. -/
def DivisibilityLT (a b : SemanticAddress) : Prop :=
  a.val ∣ b.val ∧ a.val ≠ b.val

lemma wellFounded_divisibility : WellFounded DivisibilityLT :=
  Subrelation.wf (r := InvImage (· < ·) SemanticAddress.val)
    (fun {a b} (h : DivisibilityLT a b) => Nat.lt_of_le_of_ne (Nat.le_of_dvd b.pos h.1) h.2)
    (InvImage.wf SemanticAddress.val Nat.lt_wfRel.wf)

instance : WellFoundedRelation SemanticAddress where
  rel := DivisibilityLT
  wf := wellFounded_divisibility

/-- The discrete counterpart to the FTNILO amplitude contraction.
    Returns 1 if b is a discrete successor of a generated by exactly one prime multiplication, 0 if 'jammed'. -/
noncomputable def tensorGate (a b : SemanticAddress) : ℕ :=
  let fa := a.val.factorization
  let fb := b.val.factorization
  let S := fa.support ∪ fb.support
  S.sum (fun p =>
    let delta_k := if fb p == fa p + 1 then 1 else 0
    let prod_j := (S.erase p).prod (fun q => if fb q == fa q then 1 else 0)
    delta_k * prod_j
  )

noncomputable def maximalProperDivisor (a : SemanticAddress) : SemanticAddress :=
  ⟨a.val / a.val.minFac, Nat.div_pos (Nat.minFac_le a.pos) (Nat.minFac_pos a.val)⟩

/-- The kinematic sieve operator H_hat navigating the graph.
    Termination is guaranteed by the WellFoundedRelation on SemanticAddress. -/
noncomputable def kinematicSieve (a : SemanticAddress) : ℕ :=
  if h_one : a.val == 1 then
    1 -- Base token reached successfully
  else
    let prev := maximalProperDivisor a
    let amplitude := tensorGate prev a
    if amplitude == 0 then
      0 -- Logical Jamming: Factorization constraint violated
    else
      -- Recursively sieve through the maximal proper divisor.
      have _ : DivisibilityLT prev a := by
        dsimp [DivisibilityLT, maximalProperDivisor, prev]
        constructor
        · exact Nat.div_dvd_of_dvd (Nat.minFac_dvd a.val)
        · intro contra
          have h_neq : a.val ≠ 1 := by
            intro eq1
            have : (a.val == 1) = true := beq_iff_eq.mpr eq1
            rw [this] at h_one
            contradiction
          cases Nat.div_eq_self.mp contra with
          | inl h_zero => exact ne_of_gt a.pos h_zero
          | inr h_min_one => exact h_neq (Nat.minFac_eq_one_iff.mp h_min_one)
      kinematicSieve prev
termination_by a

end KinematicRiemann
