import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Data.Nat.Factors
import TensorSieve.Kinematics

namespace KinematicRiemann

/-- Computable helper to count prime factors with multiplicity. -/
def countFactors (n : ℕ) : ℕ :=
  if h : n > 1 then
    have h1 : 1 < n.minFac := (Nat.minFac_prime (ne_of_gt h)).one_lt
    have h2 : n / n.minFac < n := Nat.div_lt_self (Nat.lt_trans (by decide) h) h1
    1 + countFactors (n / n.minFac)
  else 0
termination_by n

/-- The Local Degree (D)
    Evaluates the arithmetic divergence strictly through the finite localized
    p-adic history by summing the prime multiplicities. -/
def compLocalDegree (a : SemanticAddress) : ℕ :=
  countFactors a.val

/-- The FTNILO Delta Constraint (Tensor Gate)
    Evaluates to 1 if and only if `b` is generated by exactly one prime
    multiplication from `a`. This enforces the Kronecker delta array:
    one valuation increases by 1, all others remain identical. -/
def compTensorGate (a b : SemanticAddress) : ℕ :=
  if a.val > 0 ∧ b.val % a.val == 0 then
    let p := b.val / a.val
    if p > 1 ∧ p.minFac == p then 1 else 0
  else 0

/-- The Adjacency Matrix (K)
    A symmetric relation checking if a and b are topological neighbors
    on the Bruhat-Tits tree. -/
def compAdjacency (a b : SemanticAddress) : ℕ :=
  if compTensorGate a b == 1 ∨ compTensorGate b a == 1 then 1 else 0

/-- The Combinatorial Laplacian (L_c = D - K)
    Calculates the spatial tension purely through divisibility logic. -/
def compCombinatorialLaplacian (a b : SemanticAddress) : ℤ :=
  if a.val == b.val then
    (compLocalDegree a : ℤ)
  else if compAdjacency a b == 1 then
    -1
  else
    0

/-- Critical Bottleneck Evaluator
    A bottleneck occurs when the operator seeks a valid transition path toward a target,
    but the tensor gates yield zero amplitude, forcing the local degree to dominate
    the spectral weight and executing a logical jam. -/
def transitionAmplitude (a b : SemanticAddress) : ℤ :=
  let L_c := compCombinatorialLaplacian a b
  let phi := compTensorGate a b
  if phi == 1 then
    L_c
  else
    0

/-- Computable maximal proper divisor -/
def compMaximalProperDivisor (a : SemanticAddress) : SemanticAddress :=
  ⟨a.val / a.val.minFac, Nat.div_pos (Nat.minFac_le a.pos) (Nat.minFac_pos a.val)⟩

/-- Computable Kinematic Sieve Operator \hat{H}
    Evaluates the transition between a node's maximal proper divisor and the node itself. -/
def operatorH (a : SemanticAddress) : ℤ :=
  let prev := compMaximalProperDivisor a
  transitionAmplitude prev a

/-- Sequence of Algorithmic Halting (Energy Landscape Emission)
    Walks downward via maximalProperDivisor.
    Returns a list of tuples: (level, address, amplitude, localDegree, jammed).
    Jammed is 1 if amplitude is 0 (bottleneck), otherwise 0. -/
def emissionSpectrumDown (start : ℕ) (steps : ℕ) : List (ℕ × ℕ × ℤ × ℕ × ℕ) :=
  let rec loop (x : ℕ) (n : ℕ) (acc : List (ℕ × ℕ × ℤ × ℕ × ℕ)) :=
    match n with
    | 0 => acc.reverse
    | n' + 1 =>
        if h : x > 1 then
          let a : SemanticAddress := ⟨x, Nat.lt_trans (by decide) h⟩
          let amp := operatorH a
          let deg := compLocalDegree a
          let jammed := if amp == 0 then 1 else 0
          let next_x := (compMaximalProperDivisor a).val
          loop next_x n' ((steps - n', x, amp, deg, jammed) :: acc)
        else
          acc.reverse
  loop start steps []

end KinematicRiemann
